# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(default='title', max_length=200)),
                ('name_text', models.CharField(default='name', max_length=20)),
                ('subtitle_text', models.CharField(default='subtitle', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='LinkToPostStatic',
            fields=[
                ('name_text', models.CharField(default='name', max_length=10, primary_key=True, serialize=False)),
                ('link_text', models.CharField(default='posts/static_html/', max_length=200)),
                ('title_text', models.CharField(default='title', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('name_text', models.CharField(max_length=200)),
                ('link_text', models.CharField(default='posts/static_pdf/', max_length=200, primary_key=True, serialize=False)),
                ('title_text', models.CharField(default='title', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('link_text', models.CharField(default='posts/static_html/quick_link/', max_length=200, primary_key=True, serialize=False)),
                ('title_text', models.CharField(default='title', max_length=200)),
            ],
        ),
    ]
