# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(default='category', max_length=50)),
                ('title_text', models.CharField(default='title', max_length=200)),
                ('name_text', models.CharField(default='name', max_length=20)),
                ('subtitle_text', models.CharField(default='subtitle', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='LinkToPostStatic',
            fields=[
                ('link_text', models.CharField(default='posts/static_html/', max_length=200, primary_key=True, serialize=False)),
                ('title_text', models.CharField(default='title', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('link_text', models.CharField(default='posts/static_html/quick_link/', max_length=200, primary_key=True, serialize=False)),
                ('title_text', models.CharField(default='title', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index_page.Article')),
                ('symbol_text', models.CharField(max_length=8)),
            ],
            bases=('index_page.article',),
        ),
    ]
