# Generated by Django 2.0.1 on 2018-01-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
