# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_text',
            field=models.CharField(default='category', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='name_text',
            field=models.CharField(default='code_name', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle_text',
            field=models.CharField(default='subtitle', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 13, 31, 26, 900666, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_text',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
