# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(default='name', max_length=20)),
                ('title_text', models.CharField(default='title', max_length=200)),
                ('subtitle_text', models.CharField(default='subtitle', max_length=200)),
                ('author_text', models.CharField(default='author_name', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
