# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='name_text',
            field=models.CharField(default='name', max_length=20, primary_key=True, serialize=False),
        ),
    ]
