# Generated by Django 2.0.1 on 2018-01-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180106_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_text',
        ),
    ]
