# Generated by Django 2.0.1 on 2018-01-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_article_author_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='content_text',
        ),
    ]
