# Generated by Django 2.0.1 on 2018-01-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180107_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='foreword_text',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='hidden_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='link_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_text',
            field=models.CharField(default='name', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle_text',
            field=models.CharField(default='subtitle', max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_text',
            field=models.CharField(default='title', max_length=256),
        ),
    ]
