# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_list', '0002_auto_20171102_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
